import type { TemplateVariable, GeneratedGAS, GASExportOptions } from "@/types/template";

const VALID_JS_ID = /^[A-Za-z_$][\w$]*$/;

/**
 * Generate a Google Apps Script function from a template.
 */
export function generateGASFunction(
  templateHtml: string,
  variables: TemplateVariable[],
  options: GASExportOptions
): GeneratedGAS {
  const warnings: string[] = [];
  let functionName = options.functionName || "generateDocument";
  if (!VALID_JS_ID.test(functionName)) {
    warnings.push(`ชื่อฟังก์ชัน "${functionName}" ไม่ถูกต้อง ใช้ "generateDocument" แทน`);
    functionName = "generateDocument";
  }

  // Minify HTML: collapse whitespace between tags only, preserve text spacing
  const minifiedHtml = templateHtml
    .replace(/>\s+</g, "><")
    .replace(/\n\s*/g, " ")
    .trim();

  // Build variable documentation
  const varDocs = variables
    .map((v) => {
      const type = v.isList ? `string[] (delimiter: "${v.delimiter || ","}")` : "string";
      return ` *   ${v.name}: ${type}`;
    })
    .join("\n");

  // Identify list variables for repeating-row expansion
  const listVars = variables.filter((v) => v.isList && v.listValues && v.listValues.length > 0);

  // Build the data row replacement logic
  const replaceLogic = variables
    .map((v) => {
      if (v.isList && v.listValues) {
        return `  // ${v.name} is a list variable - expanded in repeating rows below`;
      }
      return `  html = html.replace(/\\{\\{${v.name}\\}\\}/g, escapeHtml(data["${v.name}"] != null ? data["${v.name}"] : ""));`;
    })
    .join("\n");

  // Build repeating-row expansion logic for GAS
  const expandLogic = listVars.length > 0
    ? `
  // Expand repeating rows for list variables
  var listVars = ${JSON.stringify(listVars.map((v) => ({ name: v.name, values: v.listValues })))};
  var rowRegex = /<tr\\b[^>]*\\bdata-repeat=["']true["'][^>]*>([\\s\\S]*?)<\\/tr>/gi;
  var match;
  while ((match = rowRegex.exec(html)) !== null) {
    var rowHtml = match[0];
    var usedVars = listVars.filter(function(lv) { return rowHtml.indexOf('{{' + lv.name + '}}') !== -1; });
    if (usedVars.length === 0) {
      html = html.replace(rowHtml, rowHtml.replace(/\\s*data-repeat=["']true["']/i, ""));
      rowRegex.lastIndex = 0;
      continue;
    }
    var maxCount = Math.max.apply(null, usedVars.map(function(lv) { return lv.values.length; }));
    var expanded = [];
    for (var i = 0; i < maxCount; i++) {
      var newRow = rowHtml.replace(/\\s*data-repeat=["']true["']/i, "");
      usedVars.forEach(function(lv) {
        newRow = newRow.replace(new RegExp('\\\\{\\\\{' + lv.name + '\\\\}\\\\}', 'g'), escapeHtml(lv.values[i] != null ? lv.values[i] : ""));
      });
      expanded.push(newRow);
    }
    html = html.replace(rowHtml, expanded.join(""));
    rowRegex.lastIndex = 0;
  }`
    : "";

  const mainFunction = `function ${functionName}(data) {
  var templateHtml = ${JSON.stringify(minifiedHtml)};
  var html = templateHtml;

  // Replace simple variables
${replaceLogic || "  // No variables to replace"}
${expandLogic}
  return html;
}`;

  const escapeHtmlFunction = `/** Escape HTML special characters */
function escapeHtml(text) {
  if (typeof text !== "string") return String(text);
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}`;

  const code = `/**
 * Generated by wordhtml Template Studio
 * Template: ${functionName}
 *
 * Expected data keys:
${varDocs || " *   (no variables defined)"}
 */
${options.includeGenerateFunction !== false ? mainFunction : ""}
${options.includeGenerateFunction !== false ? escapeHtmlFunction : ""}
${options.includeSheetIntegration ? generateSheetIntegration(functionName) : ""}
`;

  return { code: code.trim(), warnings };
}

function generateSheetIntegration(functionName: string): string {
  return `
/**
 * Generate documents for all rows in the active Google Sheet.
 * First row = headers, subsequent rows = data.
 */
function generateFromSheet() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var dataRange = sheet.getDataRange();
  var values = dataRange.getValues();

  if (values.length < 2) {
    Logger.log("Sheet needs at least a header row and one data row.");
    return;
  }

  var headers = values[0];
  var results = [];

  for (var i = 1; i < values.length; i++) {
    var row = values[i];
    var data = {};
    for (var j = 0; j < headers.length; j++) {
      data[headers[j]] = row[j];
    }
    var html = ${functionName}(data);
    results.push(html);
    // TODO: send email, create PDF, or save to Drive
    // Example: MailApp.sendEmail({ to: data["email"], subject: "Document", htmlBody: html });
  }

  Logger.log("Generated " + results.length + " documents.");
  return results;
}
`;
}
