import type { TemplateVariable, GeneratedGAS, GASExportOptions } from "@/types/template";

/**
 * Generate a Google Apps Script function from a template.
 */
export function generateGASFunction(
  templateHtml: string,
  variables: TemplateVariable[],
  options: GASExportOptions
): GeneratedGAS {
  const warnings: string[] = [];
  const functionName = options.functionName || "generateDocument";

  // Minify HTML: remove extra whitespace but preserve structure
  const minifiedHtml = templateHtml
    .replace(/>\s+</g, "><")
    .replace(/\s+/g, " ")
    .trim();

  // Build variable documentation
  const varDocs = variables
    .map((v) => {
      const type = v.isList ? `string[] (delimiter: "${v.delimiter || ","}")` : "string";
      return ` *   ${v.name}: ${type}`;
    })
    .join("\n");

  // Build the data row replacement logic
  const replaceLogic = variables
    .map((v) => {
      if (v.isList && v.listValues) {
        return `  // ${v.name} is a list variable - handled in repeating row expansion`;
      }
      return `  html = html.replace(/\\{\\{${v.name}\\}\\}/g, escapeHtml(data["${v.name}"] || ""));`;
    })
    .join("\n");

  const code = `/**
 * Generated by wordhtml Template Studio
 * Template: ${functionName}
 *
 * Expected data keys:
${varDocs || " *   (no variables defined)"}
 */
function ${functionName}(data) {
  var templateHtml = ${JSON.stringify(minifiedHtml)};
  var html = templateHtml;

  // Replace simple variables
${replaceLogic || "  // No variables to replace"}

  return html;
}

/** Escape HTML special characters */
function escapeHtml(text) {
  if (typeof text !== "string") return String(text);
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
${options.includeSheetIntegration ? generateSheetIntegration(functionName) : ""}
`;

  return { code: code.trim(), warnings };
}

function generateSheetIntegration(functionName: string): string {
  return `
/**
 * Generate documents for all rows in the active Google Sheet.
 * First row = headers, subsequent rows = data.
 */
function generateFromSheet() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var dataRange = sheet.getDataRange();
  var values = dataRange.getValues();

  if (values.length < 2) {
    Logger.log("Sheet needs at least a header row and one data row.");
    return;
  }

  var headers = values[0];
  var results = [];

  for (var i = 1; i < values.length; i++) {
    var row = values[i];
    var data = {};
    for (var j = 0; j < headers.length; j++) {
      data[headers[j]] = row[j];
    }
    var html = ${functionName}(data);
    results.push(html);
    // TODO: send email, create PDF, or save to Drive
    // Example: MailApp.sendEmail({ to: data["email"], subject: "Document", htmlBody: html });
  }

  Logger.log("Generated " + results.length + " documents.");
  return results;
}
`;
}
